### ISSUE TITLE
很不错的工程。但是怎么可以跑起来？

### ISSUE THREAD

**Issue by xinsuinizhuan** [RealChuan/Qt-Graphics#3]
Qt5.15.2 qtcreator打开后，选择VS2019 x64，编译，各种编译不过。需要什么环境，才能跑起来？
大概问题
1、git库找不到
![图片](https://github.com/RealChuan/Qt-Graphics/assets/40679769/6c82a70c-d5e6-44f8-8700-862fbad5ae3d)
2、Project ERROR: Unknown module(s) in QT: openglwidgets

**Comment by RealChuan** [comment]
https://github.com/RealChuan/Qt-Graphics/blob/main/.github/workflows/qmake.yml
